services:
  djangoapp:
    build: .
    ports:
      - "8000:8000"
    depends_on:
      - blogdb
    environment:
      DB_HOST: blogdb
      DB_PORT: 5432
      DB_NAME: blogdb
      DB_USER: postgres
      DB_PASSWORD: password
      DJANGO_SETTINGS_MODULE: BlogApplication.settings
    volumes:
      - ./logs:/app/logs

  blogdb:
    image: postgres:latest
    volumes:
      - postgres_data:/var/lib/postgresql/data
    environment:
      POSTGRES_DB: blogdb
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: password

volumes:
  postgres_data:
